README.md, docs/data/onboarding.md
Add a guide explaining how to add new datasets to the lake 🌊 
[Rendered view](https://github.com/cds-snc/data-lake/blob/docs/onboarding/docs/data/onboarding.md)
- Closes https://github.com/cds-snc/platform-core-services/issues/652
=> docs: add data onboarding guide

terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/etl.tf, terragrunt/aws/glue/etl/platform/gc-forms/scripts/generate_test_data.py, terragrunt/aws/glue/iam.tf, terragrunt/aws/glue/variables.tf, terragrunt/env/production/glue/terragrunt.hcl
Add an ETL job that generates Forms test data.
=> feat: add Forms test data Glue ETL job

.github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-plan-production.yml
Update the ETL triggers for the Terraform workflows so they will only ignore .json file changes within the directory.
=> fix: GitHub Terraform workflow ETL triggers

terragrunt/aws/glue/etl/platform/gc-forms/scripts/generate_test_data.py
Update the test ETL script to generate large Forms.
=> test: add large Forms config

.github/workflows/docker-apply-production.yml, .github/workflows/export-pull-request.yml, .github/workflows/workflow-failure.yml, export/platform/support/freshdesk/Makefile
Add a workflow to build, push and deploy updated Freshdesk export Docker images.
Update the export PR test workflow to include a test build of the Freshdesk Docker image.
=> feat: Freshdesk export Docker build and deploy

.github/workflows/docker-apply-production.yml
Update the Docker image build step to run in the correct directory so that it can find the Makefile.
- #92 
=> fix: docker apply workflow working directory

export/platform/support/freshdesk/main.py
Update the export script to raise exceptions for non-success HTTP response codes and update the contact fetch 404 response to be a warning rather than an error.
=> fix: raise exceptions for 4xx/5xx responses

.github/workflows/docker-apply-production.yml, .github/workflows/export-pull-request.yml
Update the export path filters to include the base `export` path. This will cause them to properly trigger on code changes as well as workflow changes.
=> fix: bug with export workflow path filter

docs/data/catalog/bes/crm/examples/salesforce.sql, docs/data/pipelines/bes/crm/salesforce.md, terragrunt/aws/glue/crawlers.tf
Keeping the default config for the CSV crawler
=> fix: crawler issues

terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/etl.tf, terragrunt/aws/glue/etl/bes/crm/scripts/process_salesforce.py, terragrunt/aws/glue/etl/bes/crm/scripts/requirements.txt
This ETL reads Salesforce Account and Opportunity data from S3, transforms it by joining the tables, and writes the transformed data back to S3 in Parquet format while registering it in an AWS Glue table.
=> feat: create new ETL from raw to transformed

terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/databases.tf
Add a Forms raw data crawler and database to store the schema of the unprocessed data.
=> fix: add Forms raw data crawler

terragrunt/aws/glue/etl/bes/crm/scripts/process_salesforce.py, terragrunt/aws/glue/iam.tf
Until Platform BI gets its ATO, we will be purging the raw data immediately after transforming it.
=> feat: purge Salesforce raw data after processing

terragrunt/aws/glue/etl/platform/gc_forms/process_data.py
Update the Forms ETL job to also process the historical data exports.
=> feat: add Forms historical data ETL

docs/data/catalog/platform/gc-forms/templates.md
Update the Forms dataset to list only one data owner.
=> docs: update data ownership contact

terragrunt/aws/glue/etl/platform/gc_forms/Makefile, terragrunt/aws/glue/etl/platform/gc_forms/process_data.py, terragrunt/aws/glue/etl/platform/gc_forms/process_data_test.py
Add units tests for the Forms ETL script and fix issues.
=> feat: add Forms ETL unit tests and fixes

terragrunt/aws/glue/etl/platform/gc_forms/process_data.py, terragrunt/aws/glue/etl/platform/gc_forms/process_data_test.py
Update the ETL job so that it correctly removes items that no longer exist in the Forms source data.  This will include templates, users, and their relationships that were previously exported but have since been deleted.
=> fix: remove Forms items from Transformed that no longer exist

terragrunt/aws/glue/etl/platform/gc_notify/initial_load.py
Load and transform Notify data locally to avoid memory and session timeout errors.
=> feat: script to initially load Notify data

terragrunt/aws/glue/etl/platform/gc_forms/process_data.py
Update the ETL script to set the variables once from the dict and then reuse them.  This is less error prone than continually using `get` on the dict.
=> fix: set Forms ETL vars once and then reference

docs/data/catalog/platform/gc-forms/templates.md
Update the Forms data catalog to remove the reference to the user name and email address.
=> docs: Forms remove name PII reference

terragrunt/aws/glue/etl/platform/gc_notify/process_data.py
Update the Notify ETL so that the incremental load date can be set on the job.  This will be used for the first ETL run after the initial load, after which it will default to always loading since yesterday at midnight.
=> fix: allow Notify incremental load date to be specified

terragrunt/aws/glue/etl/platform/gc_notify/initial_load.py
Update the initial load script to save the transformed data back to S3 and update the Glue table schema and partitions.
=> fix: update initial load to write to S3

docs/data/catalog/platform/gc-forms/examples/templates.sql, docs/data/catalog/platform/gc-forms/templates.md, docs/data/pipelines/platform/gc-forms/templates.md
Update the GC Forms docs with the new `Submissions` data.
- [Catalog](https://github.com/cds-snc/data-lake/blob/docs/form-submissions/docs/data/catalog/platform/gc-forms/templates.md)
- [Pipeline](https://github.com/cds-snc/data-lake/blob/docs/form-submissions/docs/data/pipelines/platform/gc-forms/templates.md)
- https://github.com/cds-snc/platform-core-services/issues/692
=> docs: add `Submissions` data catalog docs

terragrunt/aws/glue/etl/platform/gc_notify/process_data.py
Update the Notify ETL so that it can properly convert strings to Float.  This is required as the `pythonshell` Glue job runs with an older version of Pandas that still has this bug.
=> fix: bug with Notify object to float conversion

terragrunt/aws/alarms/alarms.tf
Fix the anomaly detection alarm so that it passes AWS API validation and creates as expected.
=> fix: Forms anomaly detection alarm

docs/data/catalog/platform/gc-forms/examples/templates.sql, docs/data/catalog/platform/gc-forms/templates.md
Update the GC Forms data catalog docs to include a note about the time series nature of the dataset.  Also updates the example queries to show how to retrieve only the latest extract.
=> docs: add Forms time series note to catalog docs

.github/workflows/docker-apply-staging.yml, .github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-staging.yml, .github/workflows/workflow-failure.yml, terragrunt/aws/glue/databases.tf, terragrunt/aws/glue/etl.tf, terragrunt/env/root.hcl
Add the GitHub workflows that will manage the Staging infrastructure when there are Terraform changes.
Update the failure notifier workflow so that it properly posts messages for failed Staging workflows to the correct ops Slack channel.
=> feat: add Staging infrastructure workflows

terragrunt/aws/buckets/great_expectations.tf
Adding new s3 buckets to put GX logs and website
=> feat: add s3 bucket for great_expectations

.devcontainer/devcontainer.json
=> fix: updated devcontainer tf version

terragrunt/aws/glue/etl/platform/gc_notify/process_data.py
Unpartitioned data were not saved properly, they require a slightly different workflow to be saved and registered to glue
Copy a day of prod data in staging and run the glue job. 
Make sure that the unpartitioned tables appear in glue and are populated
=> fix: unpartitoned data were not save properly

terragrunt/aws/stepfunctions/state_machines/data_lake_orchestrator.json
Activate daily job for the gold table
Ensure that the state machine includes the gold table glue job
=> feat: activate daily gold table job

terragrunt/aws/glue/databases.tf, terragrunt/env/production/env_vars.hcl, terragrunt/env/staging/env_vars.hcl
Allow for superset IAM role to perform cross account read
=> Give superset permission

.github/workflows/export_github_data.yml
Updating most recent GH exporter
=> chore: update GH exporter

terragrunt/aws/glue/locals.tf, terragrunt/env/production/env_vars.hcl, terragrunt/env/staging/env_vars.hcl
Adding github metadata tables to superset
=> feat: add github metadata tables to superset
