terragrunt/aws/buckets/locals.tf, terragrunt/aws/buckets/s3.tf
Update the S3 bucket lifecycle rules:
1. Expire non-current versions after 30 days.
2. Remove failed multipart uploads.
3. Move `Raw` bucket objects to cheaper storage over time.
- https://github.com/cds-snc/platform-core-services/issues/609
=> fix: update bucket lifecycle rules

terragrunt/aws/buckets/locals.tf
Remove the expired object delete marker rule as it is not applicable with this lifecycle rule and is causing a TF plan flip-flop.
=> fix: remove invalid expire lifecycle policy

.github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-plan-production.yml, terragrunt/aws/buckets/outputs.tf, terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/databases.tf, terragrunt/aws/glue/iam.tf, terragrunt/aws/glue/kms.tf, terragrunt/aws/glue/variables.tf, terragrunt/env/common/provider.tf, terragrunt/env/production/glue/terragrunt.hcl
Add a `glue` module that contains the resources needed to setup the AWS Glue database and crawlers for the organization data.
=> feat: add Glue database and crawlers for org data

terragrunt/aws/glue/iam.tf, terragrunt/aws/glue/kms.tf, terragrunt/env/production/glue/.terraform.lock.hcl
Update the Glue IAM and KMS key policies to allow CloudWatch to use the key for log encryption.
⚠️ This was applied locally to test.
=> fix: Glue KMS key policy allow CloudWatch

terragrunt/aws/glue/crawlers.tf
Update the account tag extract crawler to use a more descriptive table prefix.
Also enable the crawler schedules now that both have been tested.
=> fix: org account crawler table prefix

.github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-plan-production.yml, terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/kms.tf, terragrunt/aws/alarms/locals.tf, terragrunt/aws/alarms/sns.tf, terragrunt/aws/alarms/variables.tf, terragrunt/aws/glue/iam.tf, terragrunt/aws/glue/locals.tf, terragrunt/aws/glue/outputs.tf, terragrunt/env/production/alarms/terragrunt.hcl
Add CloudWatch alarms and the associated resources required to alert us when a Glue Crawler job fails.
- https://github.com/cds-snc/platform-core-services/issues/612
=> feat: add alarms for failed Glue Crawler runs

terragrunt/env/production/alarms/terragrunt.hcl
Update the Terragrunt config to correctly point to the glue module.
- #15 
- https://github.com/cds-snc/platform-core-services/issues/612
=> fix: alarm module dependency on glue

terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/iam.tf, terragrunt/aws/glue/kms.tf, terragrunt/env/production/alarms/.terraform.lock.hcl
- Add a custom classifier for crawling files that contain a JSON array of objects.
- Add Glue ETL IAM role.
=> fix: add JSON classifier and ETL IAM role

terragrunt/aws/glue/iam.tf, terragrunt/aws/glue/locals.tf
Update the Glue ETL IAM role to allow it to associate a KMS key with the Glue CloudWatch log group.
=> fix: Glue ETL role permissions

.github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-plan-production.yml, terragrunt/aws/athena/athena.tf, terragrunt/aws/athena/variables.tf, terragrunt/aws/buckets/athena.tf, terragrunt/aws/buckets/outputs.tf, terragrunt/aws/glue/iam.tf, terragrunt/env/production/athena/.terraform.lock.hcl, terragrunt/env/production/athena/terragrunt.hcl
Add an Athena workgroup and query result bucket.  This will allow queries to be run against the data lake buckets.
=> feat: add Athena workgroup

terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/etl/operations/aws/cost-and-usage-report.json
Add an export of the Cost and Usage Glue visual ETL job definition.  There is currently no way to manage visual ETL jobs using Terraform, but this will give us a backup of the job definition in case we need to revert a change.
A future PR will have a nightly sync job that checks for new or modified visual ETL jobs and creates automated PRs with the changes.
⚠️ Note that this PR also renames the existing Glue crawlers so they have a consistent naming convention.
=> feat: add Cost and Usage Glue visual ETL job

terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/eventbridge.tf, terragrunt/aws/alarms/locals.tf, terragrunt/aws/glue/etl/README.md
Add an EventBridge rule and custom CloudWatch metric to capture failed Glue jobs.  A new alarm has also been added to trigger when a failure occurs.
This PR also includes a README explaining the reason for the ETL job JSON exports.
- Close https://github.com/cds-snc/platform-core-services/issues/612
- https://github.com/cds-snc/platform-core-services/issues/622
=> feat: add CloudWatch alarm for failed Glue jobs

terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/eventbridge.tf, terragrunt/aws/alarms/locals.tf
Update Glue job failure event triggers to publish directly to SNS using the CloudWatch alarm message payload structure.  This allows us to publish to the existing SRE Bot webhook without the need for a custom Lambda.
- #23 
- https://github.com/cds-snc/platform-core-services/issues/612
=> fix: publish Glue job failures to SNS

terragrunt/aws/buckets/athena.tf, terragrunt/aws/buckets/curated.tf, terragrunt/aws/buckets/transformed.tf, terragrunt/aws/glue/iam.tf, terragrunt/env/common/common_variables.tf, terragrunt/env/terragrunt.hcl
Add S3 bucket policies and a Glue data catalog policy that allow Superset to access the data lake's transformed and curated data.
=> feat: grant cross-account access to Superset

terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/databases.tf
Split the Glue databases so that Raw and Transformed data is not co-located.
This will allow us to more easily tighten the data access permissions in Superset and prevent users from seeing database tables they do not have permission to query.
=> fix: create dedicated Raw and Transformed Glue databases

terragrunt/aws/glue/iam.tf
Update the data catalog's resource policy to limit Superset to only accessing specific databases and tables.
=> fix: update Superset access to Glue catalog

terragrunt/aws/glue/crawlers.tf
The account data source crawler only needs to run monthly as the data schema is fairly static.
=> chore: reduce account crawler frequency

.github/workflows/scripts/sync-glue-jobs.sh
Remove the fetch of the `main` branch as this is already checked out and ready to be used.
=> fix: glue sync job `main` fetch

docs/data/pipelines/operations/aws/cost-and-usage-report.md
Add documentation on the AWS CUR 2.0 data pipeline.
- [Rendered view](https://github.com/cds-snc/data-lake/blob/docs/cur-data-pipeline/docs/data/pipelines/operations/aws/cost-and-usage-report.md)
=> docs: Cost and Usage Report data pipeline

terragrunt/aws/alarms/alarms.tf
Update the Glue job failure alarm to trigger when an event has been matched. Now that the rule target has been removed, there are no longer `Invocation` metrics reported.
=> fix: Glue job failure trigger on MatchedEvents

.github/workflows/scripts/get-glue-jobs.sh
Update the Glue job sync script so that it can handle processing multiple Glue jobs returned by AWS.
=> fix: glue job sync for multiple jobs

terragrunt/aws/alarms/alarms.tf
The previous description was triggering the SRE Bot's CloudWatch error metric filter alarm.
=> chore: reword Glue Job failure alarm description

.github/workflows/scripts/sync-glue-jobs.sh
Update the Glue ETL sync job so that it can handle merge conflicts in the jobs it is attempting to sync.
=> fix: allow glue sync job to handle merge conflicts

README.md, docs/data/catalog/README.md, docs/data/catalog/template.md, docs/data/pipelines/README.md, docs/data/pipelines/template.md
Add READMEs and templates for the data catalog and data pipeline documentation.
The new folder structure can be seen by browsing this PRs branch:
https://github.com/cds-snc/data-lake/tree/docs/data-catalog-structure/docs/data
- https://github.com/cds-snc/platform-core-services/issues/627
- https://github.com/cds-snc/ADR/pull/35
=> docs: add data catalog and data pipeline readme

docs/data/catalog/README.md, docs/data/catalog/operations/aws/cost-and-usage-report.md, docs/data/pipelines/operations/aws/cost-and-usage-report.md
Update various documents with links to the AWS CUR data catalog and data pipeline.
- Closes https://github.com/cds-snc/platform-core-services/issues/627
=> docs: provide links to AWS CUR data catalog

terragrunt/aws/buckets/athena.tf, terragrunt/aws/buckets/curated.tf, terragrunt/aws/buckets/transformed.tf, terragrunt/aws/glue/iam.tf, terragrunt/env/common/common_variables.tf, terragrunt/env/terragrunt.hcl
Add the Superset Staging IAM access role to allow it access to the Data Lake.
- https://github.com/cds-snc/platform-core-services/issues/617
=> feat: grant Superset Staging access

terragrunt/aws/glue/crawlers.tf
Update the Cost and Usage Report crawler to run every day for the first 10 days of the month.  This is being done since the new month's partition key is not always added on the first day of the month.
- Closes https://github.com/cds-snc/platform-core-services/issues/633
=> fix: run CUR crawler for first 10 days of month

terragrunt/env/terragrunt.hcl
Switch from DynamoDB to the new `.tflock` file for state locking during TF apply operations.
=> feat: switch to Terraform lock file

terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/databases.tf, terragrunt/aws/glue/iam.tf
Add a Glue database and crawler to hold the GC Forms form (template) data for testing in Staging Superset.
This dataset will be refreshed ad-hoc to help with testing.
⚠️ Changes were applied locally to test.
=> feat: add temporary GC Forms test data

terragrunt/aws/buckets/glue.tf, terragrunt/aws/buckets/outputs.tf
Add an S3 bucket to hold Glue scripts that will be used to define ETL jobs.
=> feat: add AWS Glue bucket to hold scripts

terragrunt/aws/glue/etl/platform/gc-forms/scripts/generate_test_data.py
Update the Forms ETL script to generate 1 million rows of test data.
=> test: 1 million forms rows

.github/workflows/glue_job_sync.yml, .github/workflows/scripts/sync-glue-jobs.sh
Update the Glue job sync workflow to retrieve the latest jobs after the update branch has been checked out.
=> fix: retrieve glue jobs after branch checkout

terragrunt/aws/glue/etl.tf
Add a 15 minute timeout to the Forms ETL job.
=> fix: add timeout to Forms test data ETL

terragrunt/aws/glue/iam.tf, terragrunt/env/terragrunt.hcl
Remove the legacy Superset role IAM policy now that we've migrated to the new IAM roles per Glue database.
- Closes https://github.com/cds-snc/platform-core-services/issues/649
=> chore: remove legacy Superset role permissions

.github/workflows/scripts/sync-glue-jobs.sh
Update the Glue job sync so that it properly detects changes before attempting to commit them and open a PR.
Also add some extra logging details in case we have to further troubleshoot.
=> fix: Glue job sync changes detected condition

terragrunt/aws/glue/iam.tf, terragrunt/aws/glue/locals.tf, terragrunt/env/terragrunt.hcl
Update the IAM policies to all the new SupersetAthenaRead-all to read from all databases.  This role will be used to create virtual datasets that join across databases.
- https://github.com/cds-snc/cds-superset/pull/269
=> feat: grant access to the Superset read `all` IAM role

.github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-plan-production.yml, terragrunt/aws/export/platform/support/freshdesk/freshdesk.tf, terragrunt/aws/export/platform/support/freshdesk/locals.tf, terragrunt/aws/export/platform/support/freshdesk/variables.tf, terragrunt/aws/export/tasks.tf, terragrunt/aws/export/variables.tf, terragrunt/env/production/export/.terraform.lock.hcl, terragrunt/env/production/export/terragrunt.hcl
Add a scheduled Lambda function that pulls Freshdesk ticket data each day and writes it to the Raw bucket.
The Lambda's export code will be coming in a subsequent PR.
=> feat: add scheduled Lambda Freshdesk data export

.github/workflows/docker-apply-production.yml, export/platform/support/freshdesk/Makefile
Update the Docker build/push workflow to use the commit SHA to tag rather than the branch name.
Remove the extra `.PHONY` declaration in the Makefile.
=> fix: use commit SHA to tag Docker image

terragrunt/aws/alarms/outputs.tf, terragrunt/aws/export/platform/support/freshdesk/alarms.tf, terragrunt/aws/export/platform/support/freshdesk/freshdesk.tf, terragrunt/aws/export/platform/support/freshdesk/locals.tf, terragrunt/aws/export/platform/support/freshdesk/variables.tf, terragrunt/aws/export/tasks.tf, terragrunt/aws/export/variables.tf, terragrunt/env/production/export/terragrunt.hcl
Add a CloudWatch alarm to catch failed Freshdesk export runs.
=> feat: add alarms for failed Freshdesk exports

terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/databases.tf
Add a crawler and database to classify and store the `Platform / Support / Freshdesk` raw ticket data schema.
=> feat: add Platform Freshdesk raw data database

terragrunt/aws/export/platform/support/freshdesk/alarms.tf
Add a CloudWatch alarm to the Freshdesk export job that triggers if there are any `AWS/Lambda/Errors` metrics reported.
This will catch cases like Lambda failed invocations and timeouts.
=> feat: add alarm for Lambda `Errors` metric

terragrunt/aws/glue/databases.tf, terragrunt/aws/glue/locals.tf
Add a new AWS Glue database to hold the tables representing the transformed Freshdesk ticket data schema.
=> feat: add Glue database for transformed Freshdesk data

.github/workflows/etl-pull-request.yml, terragrunt/aws/glue/etl.tf, terragrunt/aws/glue/etl/platform/support/freshdesk/scripts/Makefile, terragrunt/aws/glue/etl/platform/support/freshdesk/scripts/process_tickets.py, terragrunt/aws/glue/etl/platform/support/freshdesk/scripts/process_tickets_test.py
Update the Freshdesk ETL so that it runs properly in AWS Glue 5.0.
This included:
1. Passing requirements via a requirements.txt file.
2. Ensuring timestamps are treated as such and in UTC.
3. Using the Glue configured logger.
PR also sets up a schedule to run the ETL job and updates to use flexible execution + autoscaling to save costs.
=> fix: Freshdesk ETL for Glue 5.0

docs/data/catalog/README.md, docs/data/catalog/operations/aws/cost-and-usage-report.md, docs/data/catalog/platform/support/examples/freshdesk.sql, docs/data/catalog/platform/support/freshdesk.md, docs/data/catalog/template.md, docs/data/pipelines/README.md, docs/data/pipelines/platform/support/freshdesk.md
Add docs for the new Freshdesk dataset.
Rendered views:
- [Pipeline](https://github.com/cds-snc/data-lake/blob/docs/freshdesk-dataset/docs/data/pipelines/platform/support/freshdesk.md)
- [Catalog](https://github.com/cds-snc/data-lake/blob/docs/freshdesk-dataset/docs/data/catalog/platform/support/freshdesk.md)
Additionally, this PR updates the data catalog template to use code blocks rather than bolding for labels.
=> docs: add Freshdesk data pipeline and catalog docs

terragrunt/aws/glue/locals.tf
Re-add the Operations AWS production database which was accidentally deleted while adding the Platform Support production database.
- #111
=> fix: re-add operations_aws_production database

terragrunt/aws/glue/etl/platform/support/freshdesk/scripts/process_tickets.py
Update the Freshdesk ETL so that when it is processing the new tickets it looks back a full year to see if there already a record for the ticket.
This will futher reduce the chance of ending up with duplicate tickets in the dataset.
=> feat: increase Freshdesk ETL window to 1 year

terragrunt/env/root.hcl
Allow Superset production to access the Freshdesk dataset.
⚠️  This must wait until cds-snc/cds-superset#281 has been released to prod otherwise the Terraform apply will fail since the IAM role won't exist yet.
- https://github.com/cds-snc/cds-superset/pull/281
=> feat: onboard Freshdesk data to Superset prod

terragrunt/aws/glue/crawlers.tf
Update the Freshdesk crawler to run for the first 10 days of each month.  This will catch scenarios where the first of the month falls on a weekend or holiday.
=> fix: update Freshdesk crawler to run more

export/platform/support/freshdesk/main.py, export/platform/support/freshdesk/main_test.py
Add a sleep between Freshdesk API page retrieval to avoid rate limiting errors.
=> fix: Freshdesk API rate limiting on export

terragrunt/aws/glue/iam.tf
Update the IAM policy to allow the Glue ETL role to use the custom KMS key when writing Python job logs.
- https://github.com/cds-snc/platform-core-services/issues/646
=> fix: allow `pythonshell` ETL jobs to log to CloudWatch

terragrunt/aws/buckets/raw.tf
Update the Raw bucket policy to allow S3 to replicate objects to the bucket.
=> feat: allow Forms Staging to replicate data to Raw

terragrunt/aws/glue/etl.tf, terragrunt/aws/glue/etl/platform/support/freshdesk/scripts/process_tickets.py, terragrunt/aws/glue/etl/platform/support/freshdesk/scripts/process_tickets_test.py
Update the Freshdesk ETL job to run as a `pythonshell` job rather than `glue` job. This simplifies and execution and reduces the job cost.
- Closes https://github.com/cds-snc/platform-core-services/issues/665
=> feat: switch Freshdesk ETL to pythonshell job

docs/data/catalog/platform/gc-forms/templates.md, docs/data/catalog/platform/support/freshdesk.md
Update the data catalog to consistently use `string` and `integer` as data types.
=> docs: use consistent string/integer data types

terragrunt/aws/export/platform/support/freshdesk/alarms.tf
Update the CloudWatch metric alarm so that it only triggers when the `Errors` metric is from the Freshdesk lambda function.
=> fix: alarm should only trigger for Freshdesk lambda

terragrunt/env/root.hcl
This role is no longer required now that we've setup the Superset Meta Database which allows querying across databases.
- https://github.com/cds-snc/platform-core-services/issues/689
=> chore: remove the SupersetAthenaReal-all role

terragrunt/aws/glue/iam.tf, terragrunt/aws/glue/locals.tf
As part of the removal of the SupersetAthenaRead-all IAM role, also remove all references to the `all` database.
- #155
=> fix: remove all references to `all` database

terragrunt/aws/glue/etl/platform/gc_forms/process_data.py, terragrunt/aws/glue/etl/platform/gc_forms/process_data_test.py
Update the Forms ETL so that it will not accidentally prune all transformed data if the sync job fails.
=> fix: Forms ETL delete all data accidentally

terragrunt/aws/glue/etl.tf, terragrunt/aws/glue/etl/platform/gc_forms/process_data.py, terragrunt/aws/glue/etl/platform/gc_forms/process_data_test.py
Add the ETL job that will process the new Forms data each day.
This includes a change to only read data from the last day and to throw an error if there is no data as the extract should occur everyday.
=> feat: create Forms ETL scheduled job

terragrunt/aws/glue/etl/platform/gc_forms/process_data.py
Update the `yesterday` date to include a timezone.  This is required by `awswrangler` when reading the S3 objects.
=> fix: add timezone to yesterday

docs/data/catalog/platform/gc-forms/templates.md, docs/data/pipelines/platform/gc-forms/templates.md
Update the GC Forms data catalog and pipeline docs with the `historical_data` dataset.
👁️ Rendered views:
- [Pipeline](https://github.com/cds-snc/data-lake/blob/docs/forms-historical-data/docs/data/pipelines/platform/gc-forms/templates.md)
- [Catalog](https://github.com/cds-snc/data-lake/blob/docs/forms-historical-data/docs/data/catalog/platform/gc-forms/templates.md)
=> docs: add GC Forms historical_data documentation

.github/workflows/docker-apply-production.yml, .github/workflows/export-pull-request.yml, export/platform/gc_notify/Dockerfile, export/platform/gc_notify/Makefile, export/platform/support/freshdesk/Dockerfile, export/platform/support/freshdesk/Makefile, terragrunt/aws/export/platform/gc_notify/lambda.tf, terragrunt/aws/export/platform/support/freshdesk/lambda.tf
Switch the Lambda function architecture for the export functions to `arm64`.  This change is being made as it is more performant and cheaper.
=> fix: switch export functions to arm64

docs/data/pipelines/platform/gc-forms/templates.md
Update the GC Forms pipeline docs to include the historical data source.
=> docs: add historical data to the GC Forms pipeline docs

terragrunt/aws/glue/etl/platform/gc_forms/process_data.py, terragrunt/aws/glue/etl/platform/gc_forms/process_data_test.py
The Forms team would like to be able to plot trends over time in their data, so they are expecting to have each night's export available with its `timestamp` column.
-https://github.com/cds-snc/platform-core-services/issues/648
=> fix: update Forms ETL to maintain time series nature of data

terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/databases.tf
Add the crawler and databases that will be used to classify and hold the data schema.
=> feat: add Glue crawler and databases for Notify data

terragrunt/aws/export/platform/gc_notify/kms.tf, terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/etl.tf, terragrunt/aws/glue/iam.tf
Update the Notify Glue crawler so that it can adapt to the dynamically updating source path each day.  This is required since RDS snapshot to S3 automatically prefixes the export with the export's unique name.
Also updates the IAM permissions of the Glue roles to allow them to use the Notify RDS export KMS key.
⚠️  These changes were applied locally during testing.
=> fix: Notify Glue crawler to handle dynamic source path

terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/iam.tf
After chatting with the team, we've found a better way to handle this by just reading the parquet directly and then validating with the know types of each field.
This approach removes the need to have to deal with the dynamic crawl path for each RDS snapshot export.
=> fix: remove Notify Glue crawler

terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/locals.tf, terragrunt/aws/alarms/variables.tf, terragrunt/aws/glue/outputs.tf, terragrunt/env/production/alarms/terragrunt.hcl
Add a new CloudWatch alarm and `ERROR` metric to catch errors logged by the ETL jobs.  Currently we only have an alarm when the job's state is reported as error.  This will allow us to have finer grained error alarms.
=> feat: add CloudWatch `ERROR` metric alarm for ETL logs

terragrunt/aws/glue/etl/platform/gc_notify/initial_load.py, terragrunt/aws/glue/etl/platform/gc_notify/process_data.py, terragrunt/aws/glue/etl/platform/gc_notify/tables/notification_history.json
Update the initial load and ETL script to remove Notify data that has a NULL partition column.
Update the ETL to properly handle the incremental load case for the `notification_history` table.
=> fix: remove Notify data with null partition columns

terragrunt/aws/glue/etl/platform/gc_forms/process_data.py, terragrunt/aws/glue/etl/platform/gc_forms/process_data_test.py
Update the ETL to drop the name, replace the email address with only the email domain and add a `year` partition.
Also updates the S3 write mode to `append` as we want to maintain the timeseries of data.
=> fix: Forms ETL drop name, add email suffix

terragrunt/aws/buckets/raw.tf
Update the IAM role to allow Forms to properly replicate their new processed data.
=> fix: S3 replication from Forms

docs/data/catalog/platform/gc-forms/templates.md, docs/data/pipelines/platform/gc-forms/templates.md, terragrunt/aws/glue/etl.tf, terragrunt/aws/glue/etl/platform/gc_forms/process_data.py
Update the Forms ETL to run on its nightly schedule.  Also adds date logging to show which S3 files are being read by the job.
Also updates the data docs with the latest changes.
=> feat: enable Forms ETL schedule

terragrunt/aws/glue/etl/platform/gc_forms/process_data.py, terragrunt/aws/glue/etl/platform/gc_forms/process_data_test.py
Update the ETL so that it can properly handle the `_count` fields which may or may not exist in each day's data extract.  If a count field is not present it will be set to 0 for that day's data.
Additionally, the data write has been updated to no longer update the Glue schema when the data is written back to S3.  This will prevent schema changes that would break Superset reports as new `_count` fields appear.
=> fix: support the optional count fields in the Template data

terragrunt/aws/glue/crawlers.tf
Disable the scheduled Forms schema crawler now that we have finalized the schema.  This will allow us to catch unexpected schema changes in the daily ETL runs.
=> chore: disable Forms crawler

terragrunt/aws/glue/etl/platform/gc_notify/initial_load.py
Update the initial load script to determine the date format automatically rather than setting a fixed format.
This handles cases where the timestamps do not have millisecond precision in the exported data (Notify test data):
```
YYYY-MM-DD HH:MM:SS.mmmmmm
YYYY-MM-DD HH:MM:SS
```
=> fix: Notify initial load infer date

terragrunt/aws/glue/locals.tf
Add the GC Notify database to the list of Glue catalog databases that can be accessed by Superset.
=> fix: update the list of Glue catalog databases

terragrunt/aws/glue/etl/platform/gc_notify/initial_load.py, terragrunt/aws/glue/etl/platform/gc_notify/process_data.py
Update the Notify ETL so that the data types are exported data are enforced and the incremental load only pulls yesterday's range of data.
Also prevent the Glue schema from being updated as new data is written.  This will cause an error to be thrown if data has an unexpected data type.
=> fix: Notify ETL to enforce data types

terragrunt/env/root.hcl
Add the IAM role that will be used by Superset Prod to access Forms Prod data.
=> feat: add Superset Prod IAM role for Forms data

terragrunt/aws/glue/etl/platform/gc_notify/process_data.py, terragrunt/aws/glue/etl/platform/gc_notify/tables/notification_history.json
Update the incremental load logic so that it considers the data retention period and loads the full partition(s) required to refresh the historical notification data each day.
This is required because of how the `notification_history` table is refreshed by its nightly job.
- `Current date`: April 10
- `Retention period`: 7 days
- `Reload from`: April 10 - 7 days = April 3
- `Reload partition`: April
- `Current date`: April 3
- `Retention period`: 7 days
- `Reload from`: April 3 - 7 days = March 27
- `Reload partitions`: March and April
=> fix: perform incremental loads at the partition level

terragrunt/aws/glue/etl/platform/gc_notify/process_data.py
Update the incremental load date to be a string.  This allows it to be compared to the VARCHAR dates in the RDS data export.
=> fix: Notify month start should be a string

terragrunt/aws/export/platform/gc_notify/lambda.tf, terragrunt/aws/glue/etl.tf
Setup the Notify export and ETL schedules to run each day.  This will let us confirm that the automated process works correctly in Staging before switching to the Prod datasource.
=> feat: enable Notify export and ETL schedule

terragrunt/aws/export/platform/gc_notify/locals.tf, terragrunt/aws/glue/etl.tf
Update the RDS snapshot export to pull from Notify prod.  This will allow us to perform a full data import and start validating that the prod data export and ETL works properly.
The Notify ETL is also being temporarily disabled until a full initial import is performed.
=> feat: switch to export Notify prod data

terragrunt/aws/buckets/raw.tf
Update the Raw S3 bucket policy to allow the new Notify IAM role to write objects.
=> fix: update Notify IAM role in bucket policy

terragrunt/aws/glue/etl/platform/gc_notify/Makefile, terragrunt/aws/glue/etl/platform/gc_notify/initial_load.py, terragrunt/aws/glue/etl/platform/gc_notify/initial_load_test.py, terragrunt/aws/glue/etl/platform/gc_notify/process_data_test.py
Add unit tests for the GC Notify ETL scripts.  Part of this change removes a global try/catch on the initial load script that was swallowing exceptions.
=> chore: add unit tests for the Notify ETLs

terragrunt/aws/glue/databases.tf, terragrunt/aws/glue/etl.tf
Remove the Glue raw database that was created for GC Notify data. This is no longer needed as we are able to hardcode the expect raw data schema based on Notify's RDS snapshot export.
=> chore: remove unused Notify raw Glue database

docs/data/catalog/README.md, docs/data/catalog/platform/gc-notify/examples/export.sql, docs/data/catalog/platform/gc-notify/export.md, docs/data/pipelines/README.md, docs/data/pipelines/platform/gc-notify/export.md
Add the documentation for the GC Notify dataset.
- [Pipeline docs](https://github.com/cds-snc/data-lake/blob/docs/notify/docs/data/pipelines/platform/gc-notify/export.md)
- [Catalog docs](https://github.com/cds-snc/data-lake/blob/docs/notify/docs/data/catalog/platform/gc-notify/export.md)
=> docs: add GC Notify pipeline and catalog docs

terragrunt/aws/glue/etl.tf, terragrunt/aws/glue/etl/platform/gc_notify/process_data.py, terragrunt/aws/glue/etl/platform/gc_notify/process_data_test.py
Update the path of the ETL job to be controlled by a Glue job param.
=> fix: update Notify ETL Raw bucket path

docs/data/pipelines/bes/crm/salesforce.md, docs/data/pipelines/operations/aws/cost-and-usage-report.md, docs/data/pipelines/platform/gc-forms/templates.md, docs/data/pipelines/platform/gc-notify/export.md, docs/data/pipelines/platform/support/freshdesk.md, docs/data/pipelines/template.md
Update the pipeline docs with a section providing the schedule and point of contact for the data pipeline.
Also fixes a discrepancy in the GC Forms pipeline docs.
=> docs: add pipeline ownership do the docs

terragrunt/aws/glue/etl.tf, terragrunt/aws/glue/etl/platform/gc_notify/process_data.py, terragrunt/aws/glue/etl/platform/gc_notify/process_data_test.py
Update the Notify ETL so that it is a Spark job.  This will give us access to more powerful workers and help address the out-of-memory errors we were seeing with prod data running in a `pythonshell` job.
=> fix: switch Notify ETL to a Spark job

terragrunt/aws/glue/etl/platform/gc_notify/process_data.py
Update the published ETL metrics to use the Notify table name rather than the full path.  This will properly group them since the path contains a date, which was causing unique metrics per run.
=> fix: group Notify CloudWatch metrics by table_name

terragrunt/aws/alarms/alarms.tf
Add a CloudWatch anomaly detection alarm to catch unexpected number of records being processed over time.
This is set to not alarm while we evaluate if it will work for us.
=> feat: add GC Forms user dataset anomaly detection alarm

terragrunt/aws/glue/etl/platform/gc_forms/process_data.py
deliveryemaildestination field was not properly cleaned-up. This is because the field was missing in the parameters
https://github.com/cds-snc/platform-core-services/issues/736#event-17591700799
@cds-snc/platform-core-services
=> Added missing email field in parameters

terragrunt/aws/export/platform/gc_notify/lambda.tf, terragrunt/aws/export/platform/gc_notify/locals.tf, terragrunt/aws/export/platform/gc_notify/variables.tf, terragrunt/aws/export/platform/support/freshdesk/lambda.tf, terragrunt/aws/export/platform/support/freshdesk/locals.tf, terragrunt/aws/export/platform/support/freshdesk/variables.tf, terragrunt/aws/export/tasks.tf, terragrunt/aws/glue/crawlers.tf, terragrunt/aws/glue/etl.tf, terragrunt/aws/glue/locals.tf, terragrunt/env/staging/alarms/.terraform.lock.hcl, terragrunt/env/staging/alarms/terragrunt.hcl, terragrunt/env/staging/athena/.terraform.lock.hcl, terragrunt/env/staging/athena/terragrunt.hcl, terragrunt/env/staging/buckets/.terraform.lock.hcl, terragrunt/env/staging/buckets/terragrunt.hcl, terragrunt/env/staging/env_vars.hcl, terragrunt/env/staging/export/.terraform.lock.hcl, terragrunt/env/staging/export/terragrunt.hcl, terragrunt/env/staging/glue/.terraform.lock.hcl, terragrunt/env/staging/glue/terragrunt.hcl
Add the Terragrunt configuration for a Staging environment and update the scheduled tasks to continue running Prod exports but disable them in Staging.
This PR will not be creating any Staging resources as the new AWS account does not exist yet.
It is expected that there is no Terraform plan for this change since it does not change the Prod infrastructure state and the workflows to create Staging infrastructure do not exist yet.
=> feat: Staging environment config setup

terragrunt/aws/glue/iam.tf, terragrunt/aws/glue/locals.tf
Update the Glue cross account IAM policy so that only databases with a corresponding Superset IAM role are included.
=> fix: Glue cross account access policy

terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/locals.tf
Add anomaly detection alarms for all nightly ETLs run against the `Platform / GC Forms` datasets and a sampling of `Platform / GC Notify` datasets.
1. These alarms will only be created in Prod.
2. This PR should merge after the Release Please setup PR has merged:
- #250
=> feat: create anomaly detection alarms for GC Forms

terragrunt/aws/glue/etl/platform/support/freshdesk/process_tickets.py, terragrunt/aws/glue/etl/platform/support/freshdesk/process_tickets_test.py, terragrunt/aws/glue/etl/platform/support/freshdesk/requirements.txt
Add CloudWatch metrics for the Freshdesk ETL.  These will be used by the CloudWatch anomaly detection alarms.
=> feat: publish Freshdesk ETL CloudWatch metrics

docs/data/catalog/platform/gc-forms/templates.md
Update the field definition to make it clear that the data is only an email domain.
- https://github.com/cds-snc/platform-core-services/issues/736
=> docs: update Forms `deliveryemaildestination` description

terragrunt/aws/glue/etl.tf
Update the Notify ETL job to start 3 hours after the RDS export has started. This is being done because we caught an error today where the export had not finished in the current 1 hour gap between export and ETL.
=> fix: delay Notify ETL by 3 hours after RDS export

.github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-staging.yml, terragrunt/aws/glue/etl/platform/gc_notify/process_data.py, terragrunt/aws/glue/etl/platform/gc_notify/process_data_test.py, terragrunt/aws/glue/etl/platform/gc_notify/tables/notification_history.json
Double the amount of days the incremental load looks back and reloads month partitions for.  This is being done because we noticed that on May 8/9, new records on April 29/30 were in the `notification_history` table, but missed as the retention period of 7 days would only have loaded the May data.
This PR also updates the `retention_days` config to `look_back_days` to be more inline with how this value is treated for the data load.
- Closes https://github.com/cds-snc/platform-core-services/issues/740
=> fix: increase the look back days for the `notification_history` load

terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/locals.tf, terragrunt/aws/alarms/variables.tf, terragrunt/aws/glue/locals.tf, terragrunt/aws/glue/outputs.tf, terragrunt/env/production/alarms/terragrunt.hcl, terragrunt/env/staging/alarms/terragrunt.hcl
Update the CloudWatch metric filters and alarms so that they properly catch `ERROR` logs in the log groups for both Spark and Pythonshell ETL job types.
⚠️ Note that it is expected that this PR will destroy the existing `glue_etl_error` CloudWatch metric filter and alarm.
=> fix: CloudWatch metric filter alarms for ETL jobs

terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/locals.tf, terragrunt/aws/alarms/logs.tf
Update the `pythonshell` CloudWatch alarm so that it does not trigger for missing GC Forms historical data.
Add saved Log Insight queries to make it easier to troubleshoot alarms.
=> fix: skip missing Forms historical data error alarms

terragrunt/aws/buckets/outputs.tf
Forgot to add a terraform output statement - terraform succeeded because it used the mocked values that were properly setup
=> fix: Missing terraform output statement

terragrunt/aws/glue/etl/platform/gc_notify/process_data.py, terragrunt/aws/glue/etl/platform/gc_notify/process_data_test.py, terragrunt/aws/glue/etl/platform/gc_notify/requirements_dev.txt, terragrunt/aws/glue/iam.tf
Check that for each table processed in the Notify dataset, the number of rows is within 2 standard deviations from the mean number of rows processed over the past 2 weeks.
If the number of rows processed is anomalous, the error log will trigger a CloudWatch metric alarm.
=> feat: add Notify dataset anomaly detection

terragrunt/aws/glue/etl/platform/gc_forms/process_data.py
GX was not saving the results to S3... The data stores behave differently than the site-docs
Run Glue job & ensure files are saved to s3
=> fix: gx not saving output to s3

terragrunt/aws/alarms/locals.tf
Do not trigger a CloudWatch alarm for pip dependency resolver errors.  These occur because of how Glue jobs install user specified dependencies.
=> chore: suppress pip dependency resolver errors

terragrunt/aws/glue/etl.tf
Data validation performs operations on the data, longer processing time is therefore expected. It took 30mns to run the job in staging instead of the previous 10 minutes.
Also, I noticed that even though we use a spark job, the data is loaded in Pandas meaning that we can't use parallelism.
A 30 mn daily job is still acceptable, but we should eventually switch to Spark DataFrames
Ensure timeout value is updated
=> fix: increased notify timeout

.github/workflows/backstage-catalog-helper.yml, .github/workflows/docker-apply-production.yml, .github/workflows/docker-apply-staging.yml, .github/workflows/etl-pull-request.yml, .github/workflows/export-pull-request.yml, .github/workflows/export_github_data.yml, .github/workflows/labels.yml, .github/workflows/ossf-scorecard.yml, .github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-production.yml, .github/workflows/terragrunt-plan-staging.yml
Update the GitHub action version pinning so that immutable commit SHAs are used.  This will make it more difficult for malicious code to be injected into our workflows.
- https://github.com/cds-snc/platform-core-services/issues/758
=> fix: pin GitHub actions to commit SHAs

terragrunt/aws/glue/etl/platform/gc_notify/process_data.py, terragrunt/aws/stepfunctions/state_machines/data_lake_orchestrator.json
A bug was introduced when converting the pandas notify ETL to a spark job where the data was appended instead of overwriting partitions.
Fixing this bug also makes the gold table glue job much quicker (3 minutes) - therefore I will reactivate it.
Notify ETL
1. Run twice in staging, make sure the data count is stable
2. Run in production, with a hard-coded value for the lookback period = 30
3. Rollback the lookback period to previous value
Gold Table
1. Run in staging with start date = 2020-01
2. Reset start_date =" "
3. Run in prod with start date = 2020-01
4. Reset start_date =" "
=> fix: Notify ETL job should overwrite data instead of appending

terragrunt/aws/glue/curated/platform/gc_notify/notification_enriched.py, terragrunt/aws/glue/etl/platform/gc_notify/process_data.py
This PR fixes two issues:
The spark ETL for Notify uses spark types that are slightly different from the previous pandas types.
This has caused newer parquet files to have a format mis-match on some column when compared with the pre-migration parquet. The Glue table metadata was still expecting the old format.
This mismatch caused a bug downstream where data with unexpected format was ignored in SQL queries
**FIX:** We can de-register and re-register the glue tables. This is light weight as its only a metadata operation.
The ETL script reads the raw tables:
- The last 2 months of data for notification_history (incremental_load=True) 
- All data in from raw bucket for other tables (incremental_load=False)
The write steps has an overwrite_partition parameter, meaning that:
- For …
=> Fix notifypipelines updates glue metadata

CHANGELOG.md
When rebasing - I ended up using the wrong commit message. Creating a "dummy" PR to trigger the release bot.
=> fix: trigger release - give superset proper access to glue
